eureka:
  client:
    service-url:
      defaultZone: http://user-eureka:euakjdaskrejdnbfjka@localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    support-equipment: support-equipment

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: mssupportequipment/logs/log-file.log



spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
